backend:
  name: git-gateway
  branch: main

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"
locale: "nl"

collections: # A list of collections the CMS should be able to edit
  - name: "nieuws" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Nieuws" # Used in the UI, ie.: "New Post"
    folder: "site/content/nieuws" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Pubicatie Datum", name: "date", widget: "datetime"}
      - {label: "Introductie", name: "description", widget: "text"}
      - {label: "Afbeelding", name: "image", widget: "image", required: false}
      - {label: "Bericht", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pagina's"
    files:
      - file: "site/content/_index.md"
        label: "Home Pagina"
        name: "home"
        fields:
          - {label: Titel, name: title, widget: string}
          - {label: Subtitel, name: subtitle, widget: string}
          - {label: Afbeelding, name: image, widget: image}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "site/content/contact/_index.md"
        label: "Contact Pagina"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Afbeelding, name: image, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Methodes
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
  - name: "site_settings"
    label: "Site Settings"
    files:
      - file: "site/data/nieuwsoverzicht.json"
        label: "Nieuws Overzicht"
        name: "nieuwsoverzicht"
        fields:
          - {label: Titel, name: title, widget: string}
          - {label: Afbeelding, name: image, widget: image}
      - file: "site/data/footer.json"
        label: Footer
        name: footer
        fields:
          - {label: Adres, name: address, widget: string}
          - {label: Postcode, name: postalcode, widget: string}
          - {label: Stad, name: city, widget: string}
          - {label: Telefoonnummer, name: phonenumber, widget: string}
          - {label: Email, name: email, widget: string}
      - file: "site/config.toml"
        label: Hugo Config
        name: config
        editor:
          preview: false
        fields:
          - {label: Site Title for Browser Tab, name: title, widget: string}
          - label: Params
            name: params
            widget: object
            fields:
              - label: Open Graph Image
                name: images
                widget: list
                field: { label: Image, name: image, widget: image }
